---

ceilometer_rabbit_vhost: ceilometer
ceilometer_rabbit_user: ceilometer
ceilometer_admin_user: ceilometer
ceilometer_domain_name: "{{ keystone_domain_name }}"
ceilometer_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
ceilometer_project_name: "{{ keystone_service_project_name | default('service') }}"

mongodb_replica_set: openstack

ceilometer_syslog_use: "{{ syslog_use | default(False) }}"

ceilometer_debug: False

keystone_rabbit_vhost: keystone
keystone_rabbit_user: keystone
glance_rabbit_vhost: glance
glance_rabbit_user: glance
nova_rabbit_vhost: nova
nova_rabbit_user: nova
neutron_rabbit_vhost: neutron
neutron_rabbit_user: neutron
cinder_rabbit_vhost: cinder
cinder_rabbit_user: cinder
heat_rabbit_vhost: heat
heat_rabbit_user: heat
swift_rabbit_vhost: swift
swift_rabbit_user: swift
trove_rabbit_vhost: trove
trove_rabbit_user: trove
sahara_rabbit_vhost: sahara
sahara_rabbit_user: sahara

ceilometer_metering_time_to_live: 0
ceilometer_event_time_to_live: 0
ceilometer_alarm_history_time_to_live: 0

ceilometer_pipeline_src: "pipeline.yaml"

#metering backend
#gnocchi only
ceilometer_store_meters: "{{ groups['gnocchi'] | count > 0 }}"
ceilometer_gnocchi_archive_policy: low

#event backend
#panko only
ceilometer_store_events: "{{ groups['panko'] | count > 0 }}"
panko_db_user: panko
panko_mysql_server: "{{ vip_mgmt }}"
panko_db: panko
panko_backend: mysql

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
SSLCACertificateFile: "{{ (SSLCACertificateFileSource is not none and SSLCACertificateFileSource | trim != '') | ternary('/etc/ssl/certs/openstack.ca.crt','') }}"
